# Generated by Django 5.2 on 2025-05-05 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_manuscript'),
    ]

    operations = [
        migrations.AddField(
            model_name='manuscript',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manuscript',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
