# Generated by Django 5.2 on 2025-05-11 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_manuscript_feedback_manuscript_is_reviewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registration',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
